### ISSUE TITLE
Unsound Sync implementation for `ImmediateIO` and `TransactionalIO`

### ISSUE THREAD

**Issue by qwaz** [edarc/max7301#1]
Hello fellow Rustacean,
we (Rust group @sslab-gatech) found a memory-safety/soundness issue in this crate while scanning Rust code on crates.io for potential vulnerabilities.

## Issue Description

https://github.com/edarc/max7301/blob/a2084de5ea1242c0fe1a143fd1719733964735a2/src/expander/immediate.rs#L23-L28

https://github.com/edarc/max7301/blob/a2084de5ea1242c0fe1a143fd1719733964735a2/src/expander/transactional.rs#L65-L70

`ImmediateIO` and `TransactionIO` implement `Sync` for `M: IOMutex<Expander<EI>>, EI: ExpanderInterface`. This bound is seemingly unsound; it allows to send a reference of `ImmediateIO` or `TransactionIO` to another thread, and from there a mutable reference of `Expander<EI>` can be accessed through `IOMutex` APIs. This could result in a thread-safety violation when `EI` is a non-Send type.

We suggest to add an `Expander<EI>: Send` bound (or an equivalent `EI: Send` bound) to those `Sync` implementations, following [the stdlib Mutex's Sync implementation](https://doc.rust-lang.org/std/sync/struct.Mutex.html#impl-Sync).

**Comment by Shnatsel** [comment]
Heads up: this issue has been included in the [RustSec advisory database](https://github.com/RustSec/advisory-db). It will be surfaced by tools such as [cargo-audit](https://github.com/RustSec/cargo-audit) or [cargo-deny](https://github.com/EmbarkStudios/cargo-deny) from now on.

Once a fix is released to crates.io, please open a pull request to update the advisory with the patched version, or file an issue on [the advisory database repository](https://github.com/RustSec/advisory-db).

**Comment by edarc** [comment]
First of all thank you @Qwaz for the report, and apologies for somehow missing the original notification.

I'll test the suggested fix as soon as I am able and publish an update.

**Comment by edarc** [comment]
This is fixed in 0.2.0. Additionally, the crate now no longer has any `unsafe` in it. I will send a PR on the advisory shortly.
